### ISSUE TITLE
[ADD] 특정 트레이너 정보 조회 뷰, 하단 사진 컬렉션 뷰 개발

### ISSUE THREAD

**Issue by Joon9750** [FIT-I/FIT-I-iOS#47]
<img width="294" alt="스크린샷 2023-02-07 오후 4 22 14" src="https://user-images.githubusercontent.com/83629193/217175705-bd99be65-4326-4828-92fa-5051e7cc66d6.png">

## Task
- [x] 사진 하단 가로 컬렉션 뷰
- [ ] 우측 상단에 '자세히 보기' 버튼 추가
- [ ] '자세히 보기' 버튼으로 갤러리 뷰로 이동
